language: node_js
node_js:
 - "node"
notifications:
  email: false
install:
- pip install --user codecov
script:
- npm run lint
- npm run test_phantomjs
- npm run build
after_success:
env:
  global:
  - secure: G1vS6GOhDNGT3CkVMOjYzQ1rdb+grH4gVLaQJgsZm1Q/npY0GUpvfSj/PpP5Hipt8Kz439/swcsotfobgnrho1Mwlx6/+GSxpXTQN921BEhfj0U4LgKNE5qQA0U+BlWjpOnKOA9/Y2Rh9u+jxG6YIxl/6dlYJ5z1W55gSGwd1bOYVAUfJkLzP8Mr6pLe1dA8oCWA/9Wcvp87IMceWcI2klyysV031PnT95aWmU1RAWyCjD4bNgn3WhwfJu8jbacgZrlggN3mPS8EzP2Q63m6LnUv/jwRnFgLMRQPVsoQkfDgnzOhOFOZjmK3TNcvlEgHFVj0HYV2j/H6170+rIrJlx1GwbqQ8PTg7/tLrQl2OxotSjHIr3qJGDV8+jUiy3zBK3RAxsjlprIbFXXSQE8wfy0G4S1N+11VPyDJIJPFt1TYEw4hZVjHaetsMGo5oB1YF39/cgGz41SnsLTj1i7IPHXVhKEJc0bdpKvBeJCXenTQZBavZVHu+J4uxRFsDOvlgTRRLN4fsnHd+3Y9nvaNnChPoRIySomMhUKFzYmV436+DpwBB3uSK/zzwvL4GwnFtVW/zPXUvPOrCRg+VPcAW2e7m7boOVHPoqR4zmSWPG9V71aOqQWTDMp0DONuoeRayELHFrZzIP7of8dpx1LDrLuSvpgLi7b6jAuVdwB6JnM=
  - secure: PWtR1+1yg+ohMU2o9VXryfShWXLYu6pDPAMLeLWOv39OALxGLAfegPc5OFd9PDoT1KfxnXhQ9OmxP6ETWZfpbWlRHpiCPKfVOvLe1bHXk0xFjSP/r+A3LaG/gXJW/HiCJ37Wncy6KtF+9Zn83dRyt+txmiv32c+8+A7obWvZeb2mriY6/ur6RpKM6+0A/TSD6fb7PT/13AfXWwqFvoXmYmo9wDBFcm5DChTS498ZtStfxeS69EM1JGx7jm6HY2dGGAXKTRc8EY3py+qqAP0wp0IMknixlOjpFada/fIENwRFTd5Ptdb6OYxGYdesVhzbEwmg+WQpYHOD4jiEkHSWnbckLvnuUfbaq5gt85QsZBhwgNsp0lZd8MwqrQ0JkeHEYiU4u1ZkW9L0wAPzTk6AuXBvq3dhlBtALf+u0CNL0VaVgZre9+wiNKvPILGORkqQSQrFg1dY9dTIYmt5Sr9M51GXzp46tObvQsUmjGU2BDtFv+JDWI+EsCqWYWzhQFp9UMS300eCd5b+v2RjSGIsE5ByYOdTDR6uefPUWmYI83Zy5I4EyLwGXNp6KUJmKOSx4DCGkKURzTGEfmd+H/iQoc9dh0ykPwszU1BZ4WYvBQIMQimt4dK33EkCxbj0ffB8WpSe+spt6VQiiIfWjvzPUsFi3Hxa278bz/Hdq4Ql9bw=